version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: my_wiremock
    ports:
      # - 8443:8443
      - 8080:8080
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh",  "--disable-gzip", "--record-mappings", "--enable-stub-cors", "--verbose"]